---
title: "Brain virome catalog and atlas"
output: html_notebook
---

```{r}
# load libraries
library(here)
library(data.table)
library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(ggpubr)
source(here::here("src/parse_sample_id.R"))
library(forcats)
```



```{r}
complete_meta_dt <- read_excel(
  here::here("metadata/complete/brain_virome_metadata.v3.xlsx")
) |>
  mutate(
    sample_ID = case_when(
      Pool == "p1733" ~ Alt_ID2,
      Pool == "p1849" ~ Alt_ID2,
      Pool == "p1894" ~ gsub("_B", "_1B", Alt_ID2),
      TRUE ~ Barcode
      ),
    tissue = `Brain Region\r\n`
    )
```

load tax tables
```{r}
tax_file_list <- c(
  here::here("data/tax_profiles/esviritu_p2058.tax_profile.tsv"),
  here::here("data/tax_profiles/esviritu_p1733.tax_profile.tsv"),
  here::here("data/tax_profiles/esviritu_p1849.tax_profile.tsv"),
  here::here("data/tax_profiles/esviritu_p1894.tax_profile.tsv")
)


esv_tax_dt <- rbindlist(lapply(tax_file_list, fread))

esv_tax_dt <- esv_tax_dt |>
  filter(
    read_count >= 10,
    !genus %in% c(
      "g__Betacoronavirus", "g__Gammaretrovirus", "g__Respirovirus",
      "g__Lentivirus", "g__Alphacoronavirus", "g__Orthorubulavirus",
      "g__Enterovirus"
      ),
    !species %in% c(
      "s__Betapapillomavirus 1", "s__Betapapillomavirus 2", 
      "s__Betapapillomavirus 3", "s__Human papillomavirus",
      "s__Triatovirus nigereginacellulae", "s__Lepidopteran ambidensovirus 1",
      "s__Scythevirus dianchis", "s__Blattambidensovirus incertum1", 
      "s__Pigeon aviadenovirus B", "s__Alphainfluenzavirus influenzae"
      ),
    !grepl("s__unclassified", species)
    ) |>
  separate(sample_ID, c("sample_ID", "Pool"), sep = "[.]") 
```

load virus commons names table
```{r}
comms_dt <- read_excel(here::here("metadata/virus_names/virus_common_names.xlsx"))

```


```{r}
esv_tax_dt |>
  group_by(species) |>
  summarize(
    n = n(),
    n_specimens = n_distinct(sample_ID)
  ) |>
  arrange(desc(n_specimens))
```


```{r}
tax_fmt_dt <- esv_tax_dt |>
  mutate(
    sample_ID = gsub("-A$", "", sample_ID),
    sample_ID = case_when(
      sample_ID == "SEVAD_BF5" ~ "SEVAD_2BF5",
      sample_ID == "SEVAD_BH5" ~ "SEVAD_1BO5",
      sample_ID == "SEVAD_BO5" ~ "SEVAD_1BO5",
      TRUE ~ sample_ID
    )
    )
```


```{r}
anti_join(
  tax_fmt_dt,
  complete_meta_dt,
  by = c("sample_ID", "Pool")
) |>
  filter(
    !grepl("CMMR", sample_ID), # remove controls
    !grepl("-B$", sample_ID), # remove alternative conditions
    !grepl("-C$", sample_ID) # remove alternative conditions
    ) 
```

```{r}
anti_join(
  complete_meta_dt,
  tax_fmt_dt,
  by = c("sample_ID", "Pool")
) |>
  filter(
    !grepl("CMMR", sample_ID), # remove controls
    Pool != "x5" # remove nonexistent pool
    ) 
# should be 43 samples that were virus-negative appearing in this anti-join
```

merge metadata and tax profiles
```{r}
merge_dt <- merge(
  tax_fmt_dt,
  complete_meta_dt,
  by = c("sample_ID", "Pool"),
  all.y = T
) |>
  filter(
    !grepl("CMMR", sample_ID), # remove controls
    Pool != "x5" # remove nonexistent pool
    ) 
```

```{r}
merge_dt |> distinct(sample_ID)
```

```{r}
merge_dt |> distinct(patient_ID)
```


```{r}
merge_dt |>
  group_by(species) |>
  summarize(
    n = n(),
    n_specimens = n_distinct(sample_ID)
  ) |>
  arrange(desc(n_specimens))
```

```{r}
merge_dt |>
  group_by(species) |>
  summarize(
    n = n(),
    n_specimens = n_distinct(sample_ID)
  ) |>
  arrange(desc(n_specimens)) |>
  filter(n_specimens >= 3)
```

```{r}


merge_comms_dt <- merge(
  merge_dt,
  comms_dt,
  by = "species",
  all.x = T
)
  
```

```{r}
merge_comms_dt |> distinct(common_name)
```




```{r}
heatmap2_p <- merge_comms_dt |>
  mutate(
    species = gsub("^s__", "", species),
    family = gsub("^f__", "", family)
    ) |>
  complete(nesting(sample_ID, tissue), nesting(species, common_name, family), fill = list(RPKMF=0)) |>
  group_by(species, common_name, family, sample_ID, tissue) |>
  summarize(RPKMF = sum(RPKMF)) |>
  filter(!is.na(tissue), !is.na(family)) |>
  ungroup() |>
  group_by(species) |>
  filter(sum(RPKMF != 0) >= 3) |>
  ungroup() |>
  ggplot(aes(
    x = sample_ID,
    y = fct_reorder(common_name, RPKMF, .fun = function(x) sum(x != 0), .desc = FALSE),
    fill = log10(RPKMF)
  )) +
  geom_tile(color = "grey25", linewidth = 0.1) +
  scale_fill_gradient2(
    low = "#f5dfbc",
    mid = "orange",
    high = "purple",
    na.value = "white",
    midpoint = -1
    #limits = c(1, NA)
  ) +
  facet_grid(c(~family, ~tissue),
             scales = "free",
             space = "free"
             ) +
  theme_bw() +
  labs(
    x = "Brain Specimens",
    y = "Virus Species (common name)",
    fill = "log10(RPKMF)"
  ) +
  theme(axis.text.x =element_blank(),
        legend.position = "bottom",
        strip.text.y = element_text(angle = 0)) 

heatmap2_p
```

```{r}
ggsave(
  here::here("charts/brain_virome_atlas_heatmap1.pdf"),
  heatmap2_p,
  width = 11,
  height = 6
)
```



```{r}
vir_sum_dt <- merge_comms_dt |>
  group_by(common_name) |>
  summarise(n = n(), perc = (n/250)*100) |>
  filter(n >= 3, !is.na(common_name)) |>
  arrange(desc(n))
```

```{r}
vir_prev_p <- vir_sum_dt |>
  mutate(label1 = paste0("n=", n, ", ", perc, "%")) |>
  ggplot(aes(
    x = perc, 
    y = fct_reorder(common_name, n, .desc = FALSE), 
    label = label1
    )
  ) +
  geom_col(fill = "grey20", width = 0.7) +
  geom_text(hjust = 0, nudge_x = 0.5, size = 3) +
  theme_bw() +
  labs(
    x = "% specimens with detection",
    y = "Virus Species (common name)"
  ) +
  lims(x = c(0, 62))

vir_prev_p
```

```{r}
ggsave(
  here::here("charts/brain_virome_species_prev1.pdf"),
  vir_prev_p,
  width = 6,
  height = 6
)
```

```{r}
sp_n_dt <- merge_comms_dt |>
  group_by(sample_ID) |>
  summarise(n = n_distinct(species, na.rm = T)) |>
  arrange(desc(n))
```

```{r}
median(sp_n_dt$n)
mean(sp_n_dt$n)
```

```{r}
sp_p <- sp_n_dt |>
  ggplot(aes(n)) +
  geom_histogram(bins = 10, fill = "grey", color = "black") +
  theme_bw() +
  labs(
    x = "# viruses detected",
    y = "specimen count"
  ) +
  scale_x_continuous(breaks = seq(0, 9, by = 1)) +
  coord_flip()

sp_p
```

```{r}
ggsave(
  here::here("charts/brain_virome_specimen_sp_count1.pdf"),
  sp_p,
  width = 6,
  height = 6
)
```





